FROM ubuntu
RUN apt-get update && apt-get -y upgrade
RUN apt install -y wget \
vim \
nmap
RUN apt install -y default-jdk
RUN mkdir /usr/local/tomcat
RUN wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.11/bin/apache-tomcat-10.0.11.tar.gz -O /tmp/tomcat.tar.gz
RUN cd /tmp && tar xvfz tomcat.tar.gz
RUN cp -Rv /tmp/apache-tomcat-10.0.11 /usr/local/tomcat
EXPOSE 8080
ENTRYPOINT /usr/local/tomcat/apache-tomcat-10.0.11/bin/catalina.sh run
