FROM ubuntu
RUN apt-get update && apt-get -y upgrade
RUN apt install -y wget \
vim \
nmap
RUN apt install -y default-jdk
RUN mkdir /usr/local/tomcat
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.36/bin/apache-tomcat-9.0.36.tar.gz -O /tmp/tomcat.tar.gz
RUN cd /tmp && tar xvfz tomcat.tar.gz
RUN cp -Rv /tmp/apache-tomcat-9.0.36 /usr/local/tomcat
EXPOSE 8080
ENTRYPOINT /usr/local/tomcat/apache-tomcat-9.0.36/bin/catalina.sh run
