FROM ubuntu
RUN apt-get update && apt-get install -y gnupg && apt-get install -y gnupg1 && apt-get install -y gnupg2 && apt-get install -y wget
RUN apt-get update
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
RUN apt-get update && apt-get install -y docker-ce --allow-unauthenticated
RUN apt-get install vim -y
 
RUN wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key

RUN sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

RUN apt-get update && apt-get install -y jenkins


RUN cat /var/lib/jenkins/secrets/initialAdminPassword (to get admin password)

RUN apt-get update
RUN curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
RUN mkdir -p /home/jenkins
RUN mkdir -p /var/lib/jenkins
RUN service jenkins start

EXPOSE 8080


